<?php

	// Regenera el archivo Entities.class.php en base al mapeo de castor
	require_once("CastorMapper.php");
	
	$mapper = new CastorMapper("mapping-mimo.xml");
	$str="<?php\r\n// Autogenerated by create_class_hierarchy.php\r\n";
	foreach(array_keys($mapper->classes) as $className){
		$parent = $mapper->classes[$className]->parent;
		$str.= "class $className";
		if($parent!=null){
			$str.=" extends ".$mapper->classes[$className]->parent;
		}
		$str.="{\r\n";
		
		foreach($mapper->classes[$className]->fields as $key=>$value){
			$str.="\tvar \$$key;\r\n";
		}
		$str.="}\r\n";
	}
	
	echo $str."\r\n?>";
	
	
	?>
