<?php
// Autogenerated by create_class_hierarchy.php
class Parametro{
	var $nombre;
	var $valor;
}
class Seccion{
	var $parametros;
}
class Configuracion{
	var $secciones;
}
class Login{
	var $usuario;
	var $clave;
}
class Error{
	var $id;
	var $descripcion;
}
class Request{
	var $login;
}
class Estado{
	var $ok;
	var $errores;
}
class Response{
	var $estado;
}
class Autor{
	var $id;
	var $nombre;
}
class AutorEjemplar{
	var $idAutor;
	var $idEjemplar;
	var $orden;
}
class Materia{
	var $id;
	var $nombre;
}
class MateriaEjemplar{
	var $idMateria;
	var $idEjemplar;
	var $orden;
}
class Ejemplar{
	var $id;
	var $referencia;
	var $titulo;
	var $edicion;
	var $editorial;
	var $precio;
	var $fechaPublicacion;
	var $fechaAlta;
	var $fechaModificacion;
	var $descripcion;
	var $observaciones;
	var $materias;
	var $autores;
}
class ParametrosBusquedaEjemplar{
	var $id;
	var $resultadosPorPagina;
	var $pagina;
	var $grupos;
}
class GrupoCriteriosBusquedaEjemplar{
	var $opcional;
	var $invertir;
	var $criterios;
}
class CriterioBusquedaEjemplar{
	var $campo;
	var $criterio;
	var $invertido;
	var $opcional;
	var $valor;
}
class ResultadoBusquedaEjemplares{
	var $pagina;
	var $numeroResultados;
	var $ejemplares;
}
class TestSetupRequest extends Request{
	var $login;
}
class TestSetupResponse extends Response{
	var $estado;
}
class AltaEjemplarRequest extends Request{
	var $login;
	var $ejemplar;
}
class ModificarEjemplarRequest extends Request{
	var $login;
	var $ejemplar;
}
class EjemplarResponse extends Response{
	var $estado;
	var $ejemplar;
}
class BuscarAutoresRequest extends Request{
	var $login;
	var $nombre;
	var $id;
	var $idEjemplar;
}
class BuscarAutoresResponse extends Response{
	var $estado;
	var $lista;
}
class BuscarMateriasRequest extends Request{
	var $login;
	var $nombre;
	var $id;
	var $idEjemplar;
}
class BuscarMateriasResponse extends Response{
	var $estado;
	var $lista;
}
class NuevaMateriaRequest extends Request{
	var $login;
	var $materia;
}
class ModificarMateriaRequest extends Request{
	var $login;
	var $materia;
}
class MateriaResponse extends Response{
	var $estado;
	var $materia;
}
class NuevoAutorRequest extends Request{
	var $login;
	var $autor;
}
class ModificarAutorRequest extends Request{
	var $login;
	var $autor;
}
class AutorResponse extends Response{
	var $estado;
	var $autor;
}
class BuscarEjemplaresRequest extends Request{
	var $login;
	var $parametros;
}
class BuscarEjemplaresResponse extends Response{
	var $estado;
	var $resultado;
}

?>